VPNNAME: MXtoAWS2
# two third pary firewall rules are defined below
# rule 1
comment1: "deny HTTPS Traffic"
policy1: deny
protocol1: tcp
destPort1: 443
destCidr1: Any
srcPort1: Any
srcCidr1: Any
syslogEnabled1: false
# rule 2
comment2: "Allow ICMP Traffic2"
policy2: allow
protocol2: icmp
destCidr2: Any
srcCidr2: Any
syslogEnabled2: false
