VPNNAME: MXtoAWS4
PINGIP: 172.31.26.184
comment1: "Deny HTTPS Traffic"
policy1: deny
protocol1: tcp
destPort1: 443
destCidr1: Any
srcPort1: Any
srcCidr1: Any
syslogEnabled1: false
comment2: "Allow ICMP Traffic2"
policy2: allow
protocol2: icmp
destCidr2: Any
srcCidr2: Any
syslogEnabled2: false
region: eu-west-1
