---
- hosts: localhost
  ignore_errors: yes
  connection: localhost
  gather_facts: False
  vars:
    count: 1
    auth_key: "{{ auth }}"
    aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
    aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
    region: "{{ REGION }}"

  vars_files:
    - config.yaml



  tasks:

    - name: include variables for devices
      include_vars:
        file: config.yaml
        #name: devices


    - name: GET The UPLINK IP
      uri:
        url: https://api.meraki.com/api/v1/organizations/265528/appliance/uplink/statuses
        method: GET
        headers:
          Content-Type: application/json
          Accept: application/json
          X-Cisco-Meraki-API-Key: "{{ auth }}"
        return_content: true
        follow_redirects: all
        validate_certs: true
      register: meraki_uplink

    #- debug:
        #msg: "{{ meraki_uplink }}"

    - name: GET Appliance Subnets
      uri:
        url: https://api.meraki.com/api/v1/devices/Q2NY-UYYZ-XVLK/appliance/dhcp/subnets
        method: GET
        headers:
          Content-Type: application/json
          Accept: application/json
          X-Cisco-Meraki-API-Key: "{{ auth }}"
        return_content: true
        follow_redirects: all
        validate_certs: true
      register: meraki_subnets

# AWS part
    - name: GET AWS Network info
      ec2_vpc_net_info:
        region: "{{ region }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_access_key: "{{ aws_access_key }}"
      register: vpc_ids

    #- debug:
        #msg: "{{ vpc_ids }}"

    - name: Create a new vgw attached to a specific VPC
      ec2_vpc_vgw:
        state: present
        region: "{{ region }}"
        vpc_id: "{{vpc_ids.vpcs.0.vpc_id}}"
        name: Ansible-VGW
        type: ipsec.1
      register: created_vgw
