---
- hosts: localhost
  ignore_errors: yes
  connection: localhost
  gather_facts: False
  vars:
    region: eu-west-1
    count: 1
    auth_key: "{{ auth }}"
  vars_files:
    - config.yaml

  tasks:

    - name: include variables for devices
      include_vars:
        file: config.yaml
        #name: devices

    - debug:
        msg: "{{VPNNAME}}"
