---
- name: meraki deployment
  hosts: localhost
  vars:
    auth_key: "{{ auth }}"

  tasks:

    - name: include variables for devices
      include_vars:
        file: config.yaml
        #name: devices

   
