name: CICD  # feel free to pick your own name

on:
  push:
    branches: 
      - master
    paths:
      - 'playbooks/**'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
           playbooks/playbook.yml
        override-deps: |
          #ansible==2.9.12
          #ansible-lint==4.3.5
        
    - shell: bash
      env:
        auth: ${{ secrets.MERAKIAPI }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PSK: ${{ secrets.PSK }}
        RTID: ${{ secrets.RTID }}
      run: sh ./scripts/entrypoint.sh

    - name: AWS SSM Send-Command
      uses: peterkimzz/aws-ssm-send-command@1.0.2
      id: ssm
      with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secret.INSTANCE_IDS }}
          working-directory: /home/ubuntu/application
          command: ls -al
          comment: Hello world!

    # Catch SSM outputs
    - name: Get the outputs
      run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
