name: CICD  # feel free to pick your own name

on:
  push:
    branches: 
      - master
    paths:
      - 'playbooks/**'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2
     
    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
           playbooks/playbook.yml
        override-deps: |
          ansible==2.9.12
          ansible-lint==4.3.3
        
    - shell: bash
      env:
        auth: ${{ secrets.MERAKIAPI }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: sh ./scripts/entrypoint.sh
