name: CICD  # feel free to pick your own name

on:
  push:
    branches: 
      - master
    paths:
      - 'playbooks/**'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
           playbooks/playbook.yml
        
    - shell: bash
      env:
        auth: ${{ secrets.MERAKIAPI }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PSK: ${{ secrets.PSK }}
        RTID: ${{ secrets.RTID }}
      run: sh ./scripts/entrypoint.sh
  
    - name: AWS SSM Send-Command
      uses: peterkimzz/aws-ssm-send-command@master
      id: ssm
      with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_IDS }}
          working-directory: /home/ubuntu
          command: ping -c 1 195.27.35.158
          comment: Ping to Public IP

    # Catch SSM outputs
    - name: Get the outputs
      run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"

    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    
    # Catch the output of the ping test
    - shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws ssm get-command-invocation --command-id ${{ steps.ssm.outputs.command-id }} --instance-id i-0b8d9c6ca369c6e34 --region eu-west-1
    
